"""Stable application error codes shown to users and written to logs."""

from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    CONFIGURATION_MISSING = "QT-CFG-001"
    CREDENTIALS_MISSING = "QT-AUTH-001"
    CREDENTIALS_INVALID = "QT-AUTH-002"
    PERMISSION_DENIED = "QT-AUTH-003"
    MARKET_DATA_CONNECTION = "QT-API-001"
    MARKET_DATA_TIMEOUT = "QT-API-002"
    MARKET_DATA_RATE_LIMIT = "QT-API-003"
    MARKET_DATA_RESPONSE = "QT-API-004"
    DATA_UNAVAILABLE = "QT-DATA-001"
    DATA_VALIDATION = "QT-DATA-002"
    DATABASE_CONNECTION = "QT-DB-001"
    DATABASE_QUERY = "QT-DB-002"
    DATABASE_WRITE = "QT-DB-003"
    CACHE_INCONSISTENT = "QT-CACHE-001"
    CHART_RENDER = "QT-CHART-001"
    USER_INPUT = "QT-UI-001"
    OPERATION_IN_PROGRESS = "QT-UI-002"
    BACKGROUND_TASK = "QT-THREAD-001"
    ALGORITHM_COMPONENT = "QT-ALG-COMPONENT-001"
    ALGORITHM_DEPENDENCY = "QT-ALG-DEPENDENCY-001"
    ALGORITHM_CONFIGURATION = "QT-ALG-CONFIG-001"
    ALGORITHM_PREVIEW = "QT-ALG-PREVIEW-001"
    ALGORITHM_STORAGE = "QT-ALG-STORAGE-001"
    FACTOR_STORAGE = "QT-FACTOR-STORAGE-001"
    FACTOR_CALCULATION = "QT-FACTOR-CALC-001"
    UNKNOWN = "QT-UNKNOWN-001"
